[package]
name = "efter-plugget"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["Robin Eklind"]
license = "0BSD"
description = "Lab report, essay and exam template for Typst."
exclude = ["inc"]
repository = "https://github.com/mewmew/efter-plugget"

[template]
path = "template"
entrypoint = "report.typ"
thumbnail = "inc/thumbnail.png"
