[package]
name = "uni-report"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["Robin Eklind"]
license = "0BSD"
description = "Lab report template for Typst."
exclude = ["inc"]
repository = "https://github.com/mewmew/uni-report"

[template]
path = "template"
entrypoint = "report.typ"
